//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorWeb.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorWeb.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Configurator.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string ARABIC {
            get {
                return ResourceManager.GetString("ARABIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string DB_CONNECTION {
            get {
                return ResourceManager.GetString("DB_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, Ask the Admin for help.
        /// </summary>
        public static string DB_FAILED_NERORK_CONNECTION {
            get {
                return ResourceManager.GetString("DB_FAILED_NERORK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Question does not exists.
        /// </summary>
        public static string DB_RECORD_NOT_EXISTS {
            get {
                return ResourceManager.GetString("DB_RECORD_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this question?.
        /// </summary>
        public static string DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ERROR_GENERAL_MESSAGE_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_GENERAL_MESSAGE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        public static string FACES {
            get {
                return ResourceManager.GetString("FACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string LABEL_STATUS {
            get {
                return ResourceManager.GetString("LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        public static string QUESTION_TYPE {
            get {
                return ResourceManager.GetString("QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed, do you still want to save it?.
        /// </summary>
        public static string SAVE_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("SAVE_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string SAVE_FAILED {
            get {
                return ResourceManager.GetString("SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successful.
        /// </summary>
        public static string SAVE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SAVE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string SERVER {
            get {
                return ResourceManager.GetString("SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string SLIDER {
            get {
                return ResourceManager.GetString("SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string STARS {
            get {
                return ResourceManager.GetString("STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Long.
        /// </summary>
        public static string STRING_LENGTH_LONG {
            get {
                return ResourceManager.GetString("STRING_LENGTH_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Short.
        /// </summary>
        public static string STRING_LENGTH_SHORT {
            get {
                return ResourceManager.GetString("STRING_LENGTH_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Successfully.
        /// </summary>
        public static string TEST_CONNECTION {
            get {
                return ResourceManager.GetString("TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string TEST_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("TEST_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors, Please check the inputs.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very long question text.
        /// </summary>
        public static string VALIDATION_ERROR_LONG_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LONG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Should be unique.
        /// </summary>
        public static string VALIDATION_ERROR_ORDER_EXIST {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ORDER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order should be less than or equal 100.
        /// </summary>
        public static string VALIDATION_ERROR_ORDER_MAX {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ORDER_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order should be greater than 0.
        /// </summary>
        public static string VALIDATION_ERROR_ORDER_MIN {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ORDER_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces number should be between 2 to 5.
        /// </summary>
        public static string VALIDATION_ERROR_QUESTION_FACES {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_QUESTION_FACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars number should be between 1 to 10.
        /// </summary>
        public static string VALIDATION_ERROR_QUESTION_STARS {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_QUESTION_STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text Required.
        /// </summary>
        public static string VALIDATION_ERROR_QUESTION_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_QUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very short question text.
        /// </summary>
        public static string VALIDATION_ERROR_SHORT_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SHORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Text Is Required.
        /// </summary>
        public static string VALIDATION_ERROR_SLIDER_CAPTION {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value should be greater than the Min Value.
        /// </summary>
        public static string VALIDATION_ERROR_SLIDER_END_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_END_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value should be less than Max Value.
        /// </summary>
        public static string VALIDATION_ERROR_SLIDER_START_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_START_VALUE", resourceCulture);
            }
        }
    }
}
