//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorWeb.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorWeb.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلق.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكيد.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما ، اطلب المساعدة من المسؤول.
        /// </summary>
        public static string DB_FAILED_NERORK_CONNECTION {
            get {
                return ResourceManager.GetString("DB_FAILED_NERORK_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السؤال غير موجود.
        /// </summary>
        public static string DB_RECORD_NOT_EXISTS {
            get {
                return ResourceManager.GetString("DB_RECORD_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف هذا السؤال؟.
        /// </summary>
        public static string DELETE_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اوجه.
        /// </summary>
        public static string FACES {
            get {
                return ResourceManager.GetString("FACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال.
        /// </summary>
        public static string LABEL_STATUS {
            get {
                return ResourceManager.GetString("LABEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال ، هل ما زلت تريد حفظه؟.
        /// </summary>
        public static string SAVE_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("SAVE_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل عملية الحفظ.
        /// </summary>
        public static string SAVE_FAILED {
            get {
                return ResourceManager.GetString("SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SAVE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("SAVE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريط.
        /// </summary>
        public static string SLIDER {
            get {
                return ResourceManager.GetString("SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجوم.
        /// </summary>
        public static string STARS {
            get {
                return ResourceManager.GetString("STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجح.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاتصال بنجاح.
        /// </summary>
        public static string TEST_CONNECTION {
            get {
                return ResourceManager.GetString("TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الاتصال.
        /// </summary>
        public static string TEST_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("TEST_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخطاء التحقق من الصحة ، يرجى التحقق من المدخلات.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص سؤال طويل جدًا.
        /// </summary>
        public static string VALIDATION_ERROR_LONG_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_LONG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الترتيب مستخدم من قبل.
        /// </summary>
        public static string VALIDATION_ERROR_ORDER_EXIST {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_ORDER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص السؤال مطلوب.
        /// </summary>
        public static string VALIDATION_ERROR_QUESTION_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_QUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص سؤال قصير جدًا.
        /// </summary>
        public static string VALIDATION_ERROR_SHORT_TEXT {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SHORT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب نص التسمية التوضيحية.
        /// </summary>
        public static string VALIDATION_ERROR_SLIDER_CAPTION {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون القيمة الدنيا أقل من القيمة القصوى.
        /// </summary>
        public static string VALIDATION_ERROR_SLIDER_VALUE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_SLIDER_VALUE", resourceCulture);
            }
        }
    }
}
